[package]
name = "anchor"
version = "0.0.0"
edition = "2024"

[dependencies]
bollard = "0.19.0"
futures-util = "0.3.31"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = [
    "macros",
    "rt-multi-thread",
    "io-std",
] }
uuid = { version = "1.17.0", features = ["v4", "serde"] }
